"""
Load the markovmodus two-state time series and split it into per-state
snapshot sequences.

Dataset (data/markovmodus/two_state_timeseries_processed.h5ad, copied from
sandbox/2026_grn_dyn/experiments/e04_markovmodus-data, generated by its
analysis/make_two_state_timeseries.py):
  - 8 destructive snapshots, t = 0..7, 2000 fresh cells each, 100 genes
  - irreversible state_0 -> state_1 switch at rate ln2/15 per unit time;
    all cells start in state_0, so state_1 is empty at t=0 and has only ~90
    cells at t=1
  - per-gene transcription -> splicing -> decay; the state only switches a
    gene's transcription rate. There is NO gene-gene regulation in the
    generator, so the structural ground truth is "no off-diagonal edges".

Expression used: log1p(normalize_total(spliced, 1e4)), computed here from the
raw spliced counts kept in layers["spliced"] -- NOT the processed X, which is
z-scored across all cells and both states and so distorts each state's own
mean and covariance. The processed file already holds all 100 genes (HVG
selection kept n_top_genes=100 of 100), so library sizes are complete.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data" / "markovmodus" / "two_state_timeseries_processed.h5ad"
TARGET_SUM = 1e4


@dataclass
class StateSeries:
    state: str
    times: np.ndarray          # snapshot times that have cells in this state
    snaps: list                # per time: (n_t, G) log-normalized expression
    n_cells: np.ndarray        # cells per snapshot
    genes: list
    target_counts: np.ndarray  # markovmodus state_expression row (spliced target)


def log_normalize(counts):
    counts = np.asarray(counts, dtype=float)
    lib = counts.sum(axis=1, keepdims=True)
    return np.log1p(counts / np.maximum(lib, 1.0) * TARGET_SUM)


def load(path=DATA, min_cells=2):
    import anndata as ad

    a = ad.read_h5ad(path)
    X = log_normalize(a.layers["spliced"])
    tp = np.asarray(a.obs["timepoint"], dtype=float)
    st = np.asarray(a.obs["state_label"].astype(str))
    labels = list(a.obs["state_label"].cat.categories)
    se = np.asarray(a.uns["state_expression"], dtype=float)
    out = {}
    for k, s in enumerate(labels):
        times, snaps = [], []
        for t in np.unique(tp):
            m = (tp == t) & (st == s)
            if m.sum() >= min_cells:
                times.append(t)
                snaps.append(X[m])
        out[s] = StateSeries(state=s, times=np.asarray(times), snaps=snaps,
                             n_cells=np.array([len(x) for x in snaps]),
                             genes=list(a.var_names), target_counts=se[k])
    return out, a
